### ISSUE TITLE
Readme Review

### ISSUE THREAD

**Issue by williamsgareth** [GarethW1994/waiter_webapp#1]
@ggsbv Please take a look when you have time. :+1:

**Comment by ggsbv** [comment]
@GarethW1994 looks perfect. Can't find any faults with it. Good job

**Comment by avermeulen** [comment]
@GarethW1994 can you add a section for MongoDB - how to connect to it see the database and connections. Also which environment variables to set. @ggsbv The same goes for yours.

**Comment by avermeulen** [comment]
@GarethW1994 What is there is looking very 👍  BTW
